### PR TITLE
Added instancing for Physgun unfreeze and toolgun fire

### PR DESCRIPTION
**Pull request by smmarkvard**

### CODE REVIEW

**Comment by Yolo-TM** [comment]
dont think its needed, because the player cant target these Entities if they are in another instance bc they dont exist for the player

**Comment by smmarkvard** [comment]
yes. Thats partly true. You can however unfreeze nearby props by pressing "R". It still affects them

**Comment by Yolo-TM** [comment]
Then we would only need to add PhysgunUnfreeze, not CanTool hook

**Comment by smmarkvard** [comment]
I have noticed that Tools can still lock on to the object

**Comment by smmarkvard** [comment]
Cuz Tools use a ray trace, and doesn't (normally) care about anything regarding about the player.

The raytrace doesn't care about the collisions of an object or if the player can see it or not

**Comment by smmarkvard** [comment]
I can send a picture if you want

**Comment by Yolo-TM** [comment]
i didnt testet it, but its gmod so everything is possible

**Pull request merged**
